### ISSUE TITLE
AttributeError: module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by DragonPwn** [xRET2pwn/PickleC2#2]
I got the following error while I'm trying to interact with my implant

![image](https://user-images.githubusercontent.com/77715054/126528622-8b039618-dc16-4db8-acea-8b4fbcdb279a.png)

**Comment by xRET2pwn** [comment]
Firstly I would like to thank you for using PickleC2.
Secondly, you can uninstall PyCrypto lib and then install PyCryptodome  and you can do that through the following commands: 

```
pip3 uninstall PyCrypto
pip3 install -U PyCryptodome
```

**Why that happens?** 
Because PyCrypto is already dead. [Reference](https://github.com/pycrypto/pycrypto/issues/173)

**Comment by DragonPwn** [comment]
thanks for helping the community, everything works fine now <3
